/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Call Sheet API
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface BodyUploadImageApiShotlistItemsItemIdUploadImagePost {
  file: Blob;
}

export type ClientDescription = string | null;

export interface Client {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  description?: ClientDescription;
  id: string;
  user_id: string;
  created_at: string;
  updated_at: string;
}

export type ClientCreateDescription = string | null;

export interface ClientCreate {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  description?: ClientCreateDescription;
}

export type ClientUpdateName = string | null;

export type ClientUpdateDescription = string | null;

export interface ClientUpdate {
  name?: ClientUpdateName;
  description?: ClientUpdateDescription;
}

export type ClientWithProjectsDescription = string | null;

export interface ClientWithProjects {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  description?: ClientWithProjectsDescription;
  id: string;
  user_id: string;
  created_at: string;
  updated_at: string;
  projects?: Project[];
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface ImageResponse {
  url: string;
}

export type ProjectDescription = string | null;

export type ProjectProductionCompany = string | null;

export type ProjectDirector = string | null;

export type ProjectProducer = string | null;

export type ProjectClientId = string | null;

export type ProjectShootDate = string | null;

export type ProjectCallTime = string | null;

export type ProjectStartTime = string | null;

export type ProjectEndTime = string | null;

export type ProjectLocation = string | null;

export interface Project {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  description?: ProjectDescription;
  production_company?: ProjectProductionCompany;
  director?: ProjectDirector;
  producer?: ProjectProducer;
  status?: ProjectStatus;
  client_id?: ProjectClientId;
  shoot_date?: ProjectShootDate;
  call_time?: ProjectCallTime;
  start_time?: ProjectStartTime;
  end_time?: ProjectEndTime;
  location?: ProjectLocation;
  id: string;
  user_id: string;
  created_at: string;
  updated_at: string;
}

export type ProjectCreateDescription = string | null;

export type ProjectCreateProductionCompany = string | null;

export type ProjectCreateDirector = string | null;

export type ProjectCreateProducer = string | null;

export type ProjectCreateClientId = string | null;

export type ProjectCreateShootDate = string | null;

export type ProjectCreateCallTime = string | null;

export type ProjectCreateStartTime = string | null;

export type ProjectCreateEndTime = string | null;

export type ProjectCreateLocation = string | null;

export interface ProjectCreate {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  description?: ProjectCreateDescription;
  production_company?: ProjectCreateProductionCompany;
  director?: ProjectCreateDirector;
  producer?: ProjectCreateProducer;
  status?: ProjectStatus;
  client_id?: ProjectCreateClientId;
  shoot_date?: ProjectCreateShootDate;
  call_time?: ProjectCreateCallTime;
  start_time?: ProjectCreateStartTime;
  end_time?: ProjectCreateEndTime;
  location?: ProjectCreateLocation;
}

export type ProjectStatus = typeof ProjectStatus[keyof typeof ProjectStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectStatus = {
  pre_production: 'pre_production',
  production: 'production',
  post_production: 'post_production',
  completed: 'completed',
} as const;

export type ProjectUpdateName = string | null;

export type ProjectUpdateDescription = string | null;

export type ProjectUpdateProductionCompany = string | null;

export type ProjectUpdateDirector = string | null;

export type ProjectUpdateProducer = string | null;

export type ProjectUpdateStatus = ProjectStatus | null;

export type ProjectUpdateClientId = string | null;

export type ProjectUpdateShootDate = string | null;

export type ProjectUpdateCallTime = string | null;

export type ProjectUpdateStartTime = string | null;

export type ProjectUpdateEndTime = string | null;

export type ProjectUpdateLocation = string | null;

export interface ProjectUpdate {
  name?: ProjectUpdateName;
  description?: ProjectUpdateDescription;
  production_company?: ProjectUpdateProductionCompany;
  director?: ProjectUpdateDirector;
  producer?: ProjectUpdateProducer;
  status?: ProjectUpdateStatus;
  client_id?: ProjectUpdateClientId;
  shoot_date?: ProjectUpdateShootDate;
  call_time?: ProjectUpdateCallTime;
  start_time?: ProjectUpdateStartTime;
  end_time?: ProjectUpdateEndTime;
  location?: ProjectUpdateLocation;
}

export type ProjectWithShotlistsDescription = string | null;

export type ProjectWithShotlistsProductionCompany = string | null;

export type ProjectWithShotlistsDirector = string | null;

export type ProjectWithShotlistsProducer = string | null;

export type ProjectWithShotlistsClientId = string | null;

export type ProjectWithShotlistsShootDate = string | null;

export type ProjectWithShotlistsCallTime = string | null;

export type ProjectWithShotlistsStartTime = string | null;

export type ProjectWithShotlistsEndTime = string | null;

export type ProjectWithShotlistsLocation = string | null;

export interface ProjectWithShotlists {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  description?: ProjectWithShotlistsDescription;
  production_company?: ProjectWithShotlistsProductionCompany;
  director?: ProjectWithShotlistsDirector;
  producer?: ProjectWithShotlistsProducer;
  status?: ProjectStatus;
  client_id?: ProjectWithShotlistsClientId;
  shoot_date?: ProjectWithShotlistsShootDate;
  call_time?: ProjectWithShotlistsCallTime;
  start_time?: ProjectWithShotlistsStartTime;
  end_time?: ProjectWithShotlistsEndTime;
  location?: ProjectWithShotlistsLocation;
  id: string;
  user_id: string;
  created_at: string;
  updated_at: string;
  shotlists?: Shotlist[];
}

export interface ReorderRequest {
  items: ShotlistItemReorder[];
}

export type ShotlistShootingDate = string | null;

export type ShotlistCallTime = string | null;

export type ShotlistWrapTime = string | null;

export type ShotlistLocation = string | null;

export type ShotlistNotes = string | null;

export interface Shotlist {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  shooting_date?: ShotlistShootingDate;
  call_time?: ShotlistCallTime;
  wrap_time?: ShotlistWrapTime;
  location?: ShotlistLocation;
  notes?: ShotlistNotes;
  id: string;
  project_id: string;
  created_at: string;
  updated_at: string;
}

export type ShotlistCreateShootingDate = string | null;

export type ShotlistCreateCallTime = string | null;

export type ShotlistCreateWrapTime = string | null;

export type ShotlistCreateLocation = string | null;

export type ShotlistCreateNotes = string | null;

export interface ShotlistCreate {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  shooting_date?: ShotlistCreateShootingDate;
  call_time?: ShotlistCreateCallTime;
  wrap_time?: ShotlistCreateWrapTime;
  location?: ShotlistCreateLocation;
  notes?: ShotlistCreateNotes;
}

export type ShotlistItemShotType = string | null;

export type ShotlistItemShotDescription = string | null;

export type ShotlistItemTimeOfDay = string | null;

export type ShotlistItemStartTime = string | null;

export type ShotlistItemNotes = string | null;

export type ShotlistItemShotReferenceImage = string | null;

export type ShotlistItemCameraAngle = string | null;

export type ShotlistItemAspectRatio = string | null;

export type ShotlistItemFps = number | null;

export type ShotlistItemScheduledTime = string | null;

export type ShotlistItemCustomPropertiesAnyOf = { [key: string]: unknown };

export type ShotlistItemCustomProperties = ShotlistItemCustomPropertiesAnyOf | null;

export interface ShotlistItem {
  /**
   * @minLength 1
   * @maxLength 100
   */
  shot_name: string;
  shot_type?: ShotlistItemShotType;
  shot_description?: ShotlistItemShotDescription;
  time_of_day?: ShotlistItemTimeOfDay;
  /**
   * @minimum 1
   * @maximum 1440
   */
  shot_duration: number;
  start_time?: ShotlistItemStartTime;
  notes?: ShotlistItemNotes;
  shot_reference_image?: ShotlistItemShotReferenceImage;
  /** @minimum 0 */
  order_index: number;
  camera_angle?: ShotlistItemCameraAngle;
  aspect_ratio?: ShotlistItemAspectRatio;
  fps?: ShotlistItemFps;
  scheduled_time?: ShotlistItemScheduledTime;
  custom_properties?: ShotlistItemCustomProperties;
  is_completed?: boolean;
  duration_locked?: boolean;
  id: string;
  shotlist_id: string;
  created_at: string;
  updated_at: string;
}

export type ShotlistItemCreateShotType = string | null;

export type ShotlistItemCreateShotDescription = string | null;

export type ShotlistItemCreateTimeOfDay = string | null;

export type ShotlistItemCreateShotDuration = number | null;

export type ShotlistItemCreateNotes = string | null;

export type ShotlistItemCreateCameraAngle = string | null;

export type ShotlistItemCreateAspectRatio = string | null;

export type ShotlistItemCreateFps = number | null;

export type ShotlistItemCreateScheduledTime = string | null;

export type ShotlistItemCreateCustomPropertiesAnyOf = { [key: string]: unknown };

export type ShotlistItemCreateCustomProperties = ShotlistItemCreateCustomPropertiesAnyOf | null;

export type ShotlistItemCreateIsCompleted = boolean | null;

export type ShotlistItemCreateDurationLocked = boolean | null;

export interface ShotlistItemCreate {
  /**
   * @minLength 1
   * @maxLength 100
   */
  shot_name: string;
  shot_type?: ShotlistItemCreateShotType;
  shot_description?: ShotlistItemCreateShotDescription;
  time_of_day?: ShotlistItemCreateTimeOfDay;
  shot_duration?: ShotlistItemCreateShotDuration;
  notes?: ShotlistItemCreateNotes;
  camera_angle?: ShotlistItemCreateCameraAngle;
  aspect_ratio?: ShotlistItemCreateAspectRatio;
  fps?: ShotlistItemCreateFps;
  scheduled_time?: ShotlistItemCreateScheduledTime;
  custom_properties?: ShotlistItemCreateCustomProperties;
  is_completed?: ShotlistItemCreateIsCompleted;
  duration_locked?: ShotlistItemCreateDurationLocked;
}

export interface ShotlistItemReorder {
  item_id: string;
  /** @minimum 0 */
  new_index: number;
}

export type ShotlistItemUpdateShotName = string | null;

export type ShotlistItemUpdateShotType = string | null;

export type ShotlistItemUpdateShotDescription = string | null;

export type ShotlistItemUpdateTimeOfDay = string | null;

export type ShotlistItemUpdateShotDuration = number | null;

export type ShotlistItemUpdateStartTime = string | null;

export type ShotlistItemUpdateNotes = string | null;

export type ShotlistItemUpdateShotReferenceImage = string | null;

export type ShotlistItemUpdateOrderIndex = number | null;

export type ShotlistItemUpdateCameraAngle = string | null;

export type ShotlistItemUpdateAspectRatio = string | null;

export type ShotlistItemUpdateFps = number | null;

export type ShotlistItemUpdateScheduledTime = string | null;

export type ShotlistItemUpdateCustomPropertiesAnyOf = { [key: string]: unknown };

export type ShotlistItemUpdateCustomProperties = ShotlistItemUpdateCustomPropertiesAnyOf | null;

export type ShotlistItemUpdateIsCompleted = boolean | null;

export type ShotlistItemUpdateDurationLocked = boolean | null;

export interface ShotlistItemUpdate {
  shot_name?: ShotlistItemUpdateShotName;
  shot_type?: ShotlistItemUpdateShotType;
  shot_description?: ShotlistItemUpdateShotDescription;
  time_of_day?: ShotlistItemUpdateTimeOfDay;
  shot_duration?: ShotlistItemUpdateShotDuration;
  start_time?: ShotlistItemUpdateStartTime;
  notes?: ShotlistItemUpdateNotes;
  shot_reference_image?: ShotlistItemUpdateShotReferenceImage;
  order_index?: ShotlistItemUpdateOrderIndex;
  camera_angle?: ShotlistItemUpdateCameraAngle;
  aspect_ratio?: ShotlistItemUpdateAspectRatio;
  fps?: ShotlistItemUpdateFps;
  scheduled_time?: ShotlistItemUpdateScheduledTime;
  custom_properties?: ShotlistItemUpdateCustomProperties;
  is_completed?: ShotlistItemUpdateIsCompleted;
  duration_locked?: ShotlistItemUpdateDurationLocked;
}

export type ShotlistUpdateName = string | null;

export type ShotlistUpdateShootingDate = string | null;

export type ShotlistUpdateCallTime = string | null;

export type ShotlistUpdateWrapTime = string | null;

export type ShotlistUpdateLocation = string | null;

export type ShotlistUpdateNotes = string | null;

export interface ShotlistUpdate {
  name?: ShotlistUpdateName;
  shooting_date?: ShotlistUpdateShootingDate;
  call_time?: ShotlistUpdateCallTime;
  wrap_time?: ShotlistUpdateWrapTime;
  location?: ShotlistUpdateLocation;
  notes?: ShotlistUpdateNotes;
}

export type ShotlistWithItemsShootingDate = string | null;

export type ShotlistWithItemsCallTime = string | null;

export type ShotlistWithItemsWrapTime = string | null;

export type ShotlistWithItemsLocation = string | null;

export type ShotlistWithItemsNotes = string | null;

export interface ShotlistWithItems {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  shooting_date?: ShotlistWithItemsShootingDate;
  call_time?: ShotlistWithItemsCallTime;
  wrap_time?: ShotlistWithItemsWrapTime;
  location?: ShotlistWithItemsLocation;
  notes?: ShotlistWithItemsNotes;
  id: string;
  project_id: string;
  created_at: string;
  updated_at: string;
  items?: ShotlistItem[];
}

export type UserFullName = string | null;

export interface User {
  id: string;
  email: string;
  full_name?: UserFullName;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type ReadClientsApiClientsGetParams = {
skip?: number;
limit?: number;
};

export type ReadProjectsApiProjectsGetParams = {
skip?: number;
limit?: number;
client_id?: string | null;
};

export type ReadShotlistsApiProjectsProjectIdShotlistsGetParams = {
skip?: number;
limit?: number;
};

export const getCallSheetAPI = () => {
/**
 * @summary Login Google
 */
const loginGoogleApiAuthLoginGoogleGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/auth/login/google`,options
    );
  }

/**
 * @summary Auth Google Callback
 */
const authGoogleCallbackApiAuthGoogleCallbackGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/auth/google/callback`,options
    );
  }

/**
 * @summary Logout
 */
const logoutApiAuthLogoutPost = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/logout`,undefined,options
    );
  }

/**
 * @summary Get Current User
 */
const getCurrentUserApiAuthMeGet = <TData = AxiosResponse<User>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/auth/me`,options
    );
  }

/**
 * @summary Read Clients
 */
const readClientsApiClientsGet = <TData = AxiosResponse<Client[]>>(
    params?: ReadClientsApiClientsGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/clients/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Create Client
 */
const createClientApiClientsPost = <TData = AxiosResponse<Client>>(
    clientCreate: ClientCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/clients/`,
      clientCreate,options
    );
  }

/**
 * @summary Read Client
 */
const readClientApiClientsClientIdGet = <TData = AxiosResponse<ClientWithProjects>>(
    clientId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/clients/${clientId}`,options
    );
  }

/**
 * @summary Update Client
 */
const updateClientApiClientsClientIdPut = <TData = AxiosResponse<Client>>(
    clientId: string,
    clientUpdate: ClientUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/clients/${clientId}`,
      clientUpdate,options
    );
  }

/**
 * @summary Delete Client
 */
const deleteClientApiClientsClientIdDelete = <TData = AxiosResponse<unknown>>(
    clientId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/clients/${clientId}`,options
    );
  }

/**
 * @summary Read Projects
 */
const readProjectsApiProjectsGet = <TData = AxiosResponse<Project[]>>(
    params?: ReadProjectsApiProjectsGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/projects/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Create Project
 */
const createProjectApiProjectsPost = <TData = AxiosResponse<Project>>(
    projectCreate: ProjectCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/projects/`,
      projectCreate,options
    );
  }

/**
 * @summary Read Project
 */
const readProjectApiProjectsProjectIdGet = <TData = AxiosResponse<ProjectWithShotlists>>(
    projectId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/projects/${projectId}`,options
    );
  }

/**
 * @summary Update Project
 */
const updateProjectApiProjectsProjectIdPut = <TData = AxiosResponse<Project>>(
    projectId: string,
    projectUpdate: ProjectUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/projects/${projectId}`,
      projectUpdate,options
    );
  }

/**
 * @summary Delete Project
 */
const deleteProjectApiProjectsProjectIdDelete = <TData = AxiosResponse<unknown>>(
    projectId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/projects/${projectId}`,options
    );
  }

/**
 * @summary Read Shotlists
 */
const readShotlistsApiProjectsProjectIdShotlistsGet = <TData = AxiosResponse<Shotlist[]>>(
    projectId: string,
    params?: ReadShotlistsApiProjectsProjectIdShotlistsGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/projects/${projectId}/shotlists`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Create Shotlist
 */
const createShotlistApiProjectsProjectIdShotlistsPost = <TData = AxiosResponse<Shotlist>>(
    projectId: string,
    shotlistCreate: ShotlistCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/projects/${projectId}/shotlists`,
      shotlistCreate,options
    );
  }

/**
 * @summary Read Shotlist
 */
const readShotlistApiShotlistsShotlistIdGet = <TData = AxiosResponse<ShotlistWithItems>>(
    shotlistId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/shotlists/${shotlistId}`,options
    );
  }

/**
 * @summary Update Shotlist
 */
const updateShotlistApiShotlistsShotlistIdPut = <TData = AxiosResponse<Shotlist>>(
    shotlistId: string,
    shotlistUpdate: ShotlistUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/shotlists/${shotlistId}`,
      shotlistUpdate,options
    );
  }

/**
 * @summary Delete Shotlist
 */
const deleteShotlistApiShotlistsShotlistIdDelete = <TData = AxiosResponse<unknown>>(
    shotlistId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/shotlists/${shotlistId}`,options
    );
  }

/**
 * @summary Read Shotlist Items
 */
const readShotlistItemsApiShotlistsShotlistIdItemsGet = <TData = AxiosResponse<ShotlistItem[]>>(
    shotlistId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/shotlists/${shotlistId}/items`,options
    );
  }

/**
 * @summary Create Shotlist Item
 */
const createShotlistItemApiShotlistsShotlistIdItemsPost = <TData = AxiosResponse<ShotlistItem>>(
    shotlistId: string,
    shotlistItemCreate: ShotlistItemCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/shotlists/${shotlistId}/items`,
      shotlistItemCreate,options
    );
  }

/**
 * @summary Read Shotlist Item
 */
const readShotlistItemApiShotlistItemsItemIdGet = <TData = AxiosResponse<ShotlistItem>>(
    itemId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/shotlist-items/${itemId}`,options
    );
  }

/**
 * @summary Update Shotlist Item
 */
const updateShotlistItemApiShotlistItemsItemIdPut = <TData = AxiosResponse<ShotlistItem>>(
    itemId: string,
    shotlistItemUpdate: ShotlistItemUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/shotlist-items/${itemId}`,
      shotlistItemUpdate,options
    );
  }

/**
 * @summary Delete Shotlist Item
 */
const deleteShotlistItemApiShotlistItemsItemIdDelete = <TData = AxiosResponse<unknown>>(
    itemId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/shotlist-items/${itemId}`,options
    );
  }

/**
 * @summary Reorder Shotlist Items
 */
const reorderShotlistItemsApiShotlistsShotlistIdItemsReorderPut = <TData = AxiosResponse<ShotlistItem[]>>(
    shotlistId: string,
    reorderRequest: ReorderRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/shotlists/${shotlistId}/items/reorder`,
      reorderRequest,options
    );
  }

/**
 * @summary Upload Image
 */
const uploadImageApiShotlistItemsItemIdUploadImagePost = <TData = AxiosResponse<ImageResponse>>(
    itemId: string,
    bodyUploadImageApiShotlistItemsItemIdUploadImagePost: BodyUploadImageApiShotlistItemsItemIdUploadImagePost, options?: AxiosRequestConfig
 ): Promise<TData> => {const formData = new FormData();
formData.append(`file`, bodyUploadImageApiShotlistItemsItemIdUploadImagePost.file)

    return axios.default.post(
      `/api/shotlist-items/${itemId}/upload-image`,
      formData,options
    );
  }

/**
 * @summary Serve Spa
 */
const serveSpaFullPathGet = <TData = AxiosResponse<unknown>>(
    fullPath: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/${fullPath}`,options
    );
  }

return {loginGoogleApiAuthLoginGoogleGet,authGoogleCallbackApiAuthGoogleCallbackGet,logoutApiAuthLogoutPost,getCurrentUserApiAuthMeGet,readClientsApiClientsGet,createClientApiClientsPost,readClientApiClientsClientIdGet,updateClientApiClientsClientIdPut,deleteClientApiClientsClientIdDelete,readProjectsApiProjectsGet,createProjectApiProjectsPost,readProjectApiProjectsProjectIdGet,updateProjectApiProjectsProjectIdPut,deleteProjectApiProjectsProjectIdDelete,readShotlistsApiProjectsProjectIdShotlistsGet,createShotlistApiProjectsProjectIdShotlistsPost,readShotlistApiShotlistsShotlistIdGet,updateShotlistApiShotlistsShotlistIdPut,deleteShotlistApiShotlistsShotlistIdDelete,readShotlistItemsApiShotlistsShotlistIdItemsGet,createShotlistItemApiShotlistsShotlistIdItemsPost,readShotlistItemApiShotlistItemsItemIdGet,updateShotlistItemApiShotlistItemsItemIdPut,deleteShotlistItemApiShotlistItemsItemIdDelete,reorderShotlistItemsApiShotlistsShotlistIdItemsReorderPut,uploadImageApiShotlistItemsItemIdUploadImagePost,serveSpaFullPathGet}};
export type LoginGoogleApiAuthLoginGoogleGetResult = AxiosResponse<unknown>
export type AuthGoogleCallbackApiAuthGoogleCallbackGetResult = AxiosResponse<unknown>
export type LogoutApiAuthLogoutPostResult = AxiosResponse<unknown>
export type GetCurrentUserApiAuthMeGetResult = AxiosResponse<User>
export type ReadClientsApiClientsGetResult = AxiosResponse<Client[]>
export type CreateClientApiClientsPostResult = AxiosResponse<Client>
export type ReadClientApiClientsClientIdGetResult = AxiosResponse<ClientWithProjects>
export type UpdateClientApiClientsClientIdPutResult = AxiosResponse<Client>
export type DeleteClientApiClientsClientIdDeleteResult = AxiosResponse<unknown>
export type ReadProjectsApiProjectsGetResult = AxiosResponse<Project[]>
export type CreateProjectApiProjectsPostResult = AxiosResponse<Project>
export type ReadProjectApiProjectsProjectIdGetResult = AxiosResponse<ProjectWithShotlists>
export type UpdateProjectApiProjectsProjectIdPutResult = AxiosResponse<Project>
export type DeleteProjectApiProjectsProjectIdDeleteResult = AxiosResponse<unknown>
export type ReadShotlistsApiProjectsProjectIdShotlistsGetResult = AxiosResponse<Shotlist[]>
export type CreateShotlistApiProjectsProjectIdShotlistsPostResult = AxiosResponse<Shotlist>
export type ReadShotlistApiShotlistsShotlistIdGetResult = AxiosResponse<ShotlistWithItems>
export type UpdateShotlistApiShotlistsShotlistIdPutResult = AxiosResponse<Shotlist>
export type DeleteShotlistApiShotlistsShotlistIdDeleteResult = AxiosResponse<unknown>
export type ReadShotlistItemsApiShotlistsShotlistIdItemsGetResult = AxiosResponse<ShotlistItem[]>
export type CreateShotlistItemApiShotlistsShotlistIdItemsPostResult = AxiosResponse<ShotlistItem>
export type ReadShotlistItemApiShotlistItemsItemIdGetResult = AxiosResponse<ShotlistItem>
export type UpdateShotlistItemApiShotlistItemsItemIdPutResult = AxiosResponse<ShotlistItem>
export type DeleteShotlistItemApiShotlistItemsItemIdDeleteResult = AxiosResponse<unknown>
export type ReorderShotlistItemsApiShotlistsShotlistIdItemsReorderPutResult = AxiosResponse<ShotlistItem[]>
export type UploadImageApiShotlistItemsItemIdUploadImagePostResult = AxiosResponse<ImageResponse>
export type ServeSpaFullPathGetResult = AxiosResponse<unknown>
