"""Add custom_properties to shotlist_items

Revision ID: 29903c28948d
Revises: 9ea7dae889db
Create Date: 2025-09-23 15:37:15.578017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29903c28948d'
down_revision: Union[str, None] = '9ea7dae889db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shotlist_items', sa.Column('scheduled_time', sa.Time(), nullable=True))
    op.add_column('shotlist_items', sa.Column('custom_properties', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shotlist_items', 'custom_properties')
    op.drop_column('shotlist_items', 'scheduled_time')
    # ### end Alembic commands ###
