"""add_duration_locked_to_shotlist_items

Revision ID: 6cb8ef52a585
Revises: a51c4ab59c52
Create Date: 2025-09-26 16:19:34.354129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb8ef52a585'
down_revision: Union[str, None] = 'a51c4ab59c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with a default value first
    op.add_column('shotlist_items', sa.Column('duration_locked', sa.Boolean(), nullable=True, default=False))
    # Update existing rows to have False
    op.execute("UPDATE shotlist_items SET duration_locked = FALSE WHERE duration_locked IS NULL")
    # Make column non-nullable
    op.alter_column('shotlist_items', 'duration_locked', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shotlist_items', 'duration_locked')
    # ### end Alembic commands ###
