"""Add new shot attributes: camera_angle, aspect_ratio, fps, shot_description

Revision ID: 7b4a9823e4a5
Revises: 
Create Date: 2025-09-21 11:02:07.922278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4a9823e4a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shotlist_items', sa.Column('camera_angle', sa.String(length=100), nullable=True))
    op.add_column('shotlist_items', sa.Column('aspect_ratio', sa.String(length=20), nullable=True))
    op.add_column('shotlist_items', sa.Column('fps', sa.Integer(), nullable=True))
    op.add_column('shotlist_items', sa.Column('shot_description', sa.Text(), nullable=True))

    # Migrate existing shot_details data to shot_description
    op.execute("UPDATE shotlist_items SET shot_description = shot_details WHERE shot_details IS NOT NULL")

    op.drop_column('shotlist_items', 'shot_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shotlist_items', sa.Column('shot_details', sa.TEXT(), autoincrement=False, nullable=True))

    # Migrate shot_description data back to shot_details
    op.execute("UPDATE shotlist_items SET shot_details = shot_description WHERE shot_description IS NOT NULL")

    op.drop_column('shotlist_items', 'shot_description')
    op.drop_column('shotlist_items', 'fps')
    op.drop_column('shotlist_items', 'aspect_ratio')
    op.drop_column('shotlist_items', 'camera_angle')
    # ### end Alembic commands ###
