"""Add time and location fields to projects

Revision ID: 9ea7dae889db
Revises: 7b4a9823e4a5
Create Date: 2025-09-23 15:27:02.422824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea7dae889db'
down_revision: Union[str, None] = '7b4a9823e4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('shoot_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('call_time', sa.Time(), nullable=True))
    op.add_column('projects', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('projects', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('projects', sa.Column('location', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'location')
    op.drop_column('projects', 'end_time')
    op.drop_column('projects', 'start_time')
    op.drop_column('projects', 'call_time')
    op.drop_column('projects', 'shoot_date')
    # ### end Alembic commands ###
